# Generated by Django 3.1 on 2020-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_maincategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory', models.CharField(max_length=200)),
                ('SubCategory_image', models.ImageField(default='subcategory/default.jpg', upload_to='subcategory/')),
                ('MainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.maincategories')),
            ],
        ),
    ]
