# Generated by Django 3.1 on 2020-10-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategories'),
        ),
    ]
